---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jarvis.
--- DateTime: 2025/8/7 21:35
---

-- 1. 参数列表
-- 1.1 voucher id
local voucherId = ARGV[1]
-- 1.2 user id
local userId = ARGV[2]
-- 1.3 order id
local orderId = ARGV[3]

-- 2. keys list
-- 2.1 stock key
local stockKey = 'seckill:stock:' .. voucherId
-- 2.2 users key
local usersKey = 'seckill:users:' .. voucherId

-- 3. script scope
-- 3.1 whether enough stock
if (tonumber(redis.call('get', stockKey)) <= 0) then
    -- 3.2 lack of stock
    return 1
end

-- 3.2 whether current user already bought
if (redis.call('sismember', usersKey, userId) == 1) then
    -- 3.3 already exists, repetitive order
    return 2
end

-- 3.4 qualified, reduce stock
redis.call('incrby', stockKey, -1)
-- 3.5 create order, save user to users set
redis.call('sadd', usersKey, userId)
-- 3.6 add msg to msg queue: XADD stream.orders * k1 v1 k2 v2
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)

-- 3 res status
return 0